/********** PLANTS ACTION TYPES *************** */

export const FETCH_PLANETS_STARTED = "FETCH_PLANETS_STARTED";
export const FETCH_PLANETS_END = "FETCH_PLANETS_END";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";

/********** CHARACTERS ACTION TYPES *************** */
export const FETCH_CHARACTERS_STARTED = "FETCH_CHARACTERS_STARTED";
export const FETCH_CHARACTERS_END = "FETCH_CHARACTERS_END";
export const FETCH_CHARACTERS_FAILURE = "FETCH_CHARACTERS_FAILURE";
export const FETCH_CHARACTERS_SUCCESS = "FETCH_CHARACTERS_SUCCESS";